### ISSUE TITLE
Migration from woocommerce to magento is not successful if user profile doesn't have country, address1 and city

### ISSUE THREAD

**Issue by encius** [expressly/woocommerce#18]
Even if the following fields are not mandatory, they are required for migration (according to event logs):
- field [country] max allowed length is [3], actual length is [5]
- field [address1 is required] is required
- field [city is required] is required

**Comment by mgsmith57** [comment]
Not a bug. Expected edge case scenario and failure. Fields are mandatory for expressly migration
