### ISSUE TITLE
When migrating from woocommerce to magento, phone is copied in magento as billing phone and shipping phone

### ISSUE THREAD

**Issue by encius** [expressly/woocommerce#20]
Have an user with full details in woocommerce (which means phone only for billing)
Start the migration process.

Actual:
Phone set in Woo - which is only one, for Billing address - is copied in Magento to Shipping address as well.

Check user enciuwoo1@example.com in test appliance.

**Comment by mgsmith57** [comment]
Woocommerce appears to return the phone number against both addresses even if it only displays it against one so closing as a quirk of the WC.
